// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	sync "sync"

	events "github.com/alphagov/paas-prometheus-exporter/events"
	eventsa "github.com/cloudfoundry/sonde-go/events"
)

type FakeAppStreamProvider struct {
	OpenStreamForStub        func(string) (<-chan *eventsa.Envelope, <-chan error)
	openStreamForMutex       sync.RWMutex
	openStreamForArgsForCall []struct {
		arg1 string
	}
	openStreamForReturns struct {
		result1 <-chan *eventsa.Envelope
		result2 <-chan error
	}
	openStreamForReturnsOnCall map[int]struct {
		result1 <-chan *eventsa.Envelope
		result2 <-chan error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeAppStreamProvider) OpenStreamFor(arg1 string) (<-chan *eventsa.Envelope, <-chan error) {
	fake.openStreamForMutex.Lock()
	ret, specificReturn := fake.openStreamForReturnsOnCall[len(fake.openStreamForArgsForCall)]
	fake.openStreamForArgsForCall = append(fake.openStreamForArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("OpenStreamFor", []interface{}{arg1})
	fake.openStreamForMutex.Unlock()
	if fake.OpenStreamForStub != nil {
		return fake.OpenStreamForStub(arg1)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.openStreamForReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeAppStreamProvider) OpenStreamForCallCount() int {
	fake.openStreamForMutex.RLock()
	defer fake.openStreamForMutex.RUnlock()
	return len(fake.openStreamForArgsForCall)
}

func (fake *FakeAppStreamProvider) OpenStreamForCalls(stub func(string) (<-chan *eventsa.Envelope, <-chan error)) {
	fake.openStreamForMutex.Lock()
	defer fake.openStreamForMutex.Unlock()
	fake.OpenStreamForStub = stub
}

func (fake *FakeAppStreamProvider) OpenStreamForArgsForCall(i int) string {
	fake.openStreamForMutex.RLock()
	defer fake.openStreamForMutex.RUnlock()
	argsForCall := fake.openStreamForArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeAppStreamProvider) OpenStreamForReturns(result1 <-chan *eventsa.Envelope, result2 <-chan error) {
	fake.openStreamForMutex.Lock()
	defer fake.openStreamForMutex.Unlock()
	fake.OpenStreamForStub = nil
	fake.openStreamForReturns = struct {
		result1 <-chan *eventsa.Envelope
		result2 <-chan error
	}{result1, result2}
}

func (fake *FakeAppStreamProvider) OpenStreamForReturnsOnCall(i int, result1 <-chan *eventsa.Envelope, result2 <-chan error) {
	fake.openStreamForMutex.Lock()
	defer fake.openStreamForMutex.Unlock()
	fake.OpenStreamForStub = nil
	if fake.openStreamForReturnsOnCall == nil {
		fake.openStreamForReturnsOnCall = make(map[int]struct {
			result1 <-chan *eventsa.Envelope
			result2 <-chan error
		})
	}
	fake.openStreamForReturnsOnCall[i] = struct {
		result1 <-chan *eventsa.Envelope
		result2 <-chan error
	}{result1, result2}
}

func (fake *FakeAppStreamProvider) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.openStreamForMutex.RLock()
	defer fake.openStreamForMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeAppStreamProvider) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ events.AppStreamProvider = new(FakeAppStreamProvider)
