// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/alphagov/paas-prometheus-exporter/cf"
	"github.com/cloudfoundry-community/go-cfclient"
)

type FakeClient struct {
	ListAppsWithSpaceAndOrgStub        func() ([]cfclient.App, error)
	listAppsWithSpaceAndOrgMutex       sync.RWMutex
	listAppsWithSpaceAndOrgArgsForCall []struct{}
	listAppsWithSpaceAndOrgReturns     struct {
		result1 []cfclient.App
		result2 error
	}
	listAppsWithSpaceAndOrgReturnsOnCall map[int]struct {
		result1 []cfclient.App
		result2 error
	}
	ListServicesWithSpaceAndOrgStub        func() ([]cf.ServiceInstance, error)
	listServicesWithSpaceAndOrgMutex       sync.RWMutex
	listServicesWithSpaceAndOrgArgsForCall []struct{}
	listServicesWithSpaceAndOrgReturns     struct {
		result1 []cf.ServiceInstance
		result2 error
	}
	listServicesWithSpaceAndOrgReturnsOnCall map[int]struct {
		result1 []cf.ServiceInstance
		result2 error
	}
	NewAppStreamProviderStub        func(appGUID string) cf.AppStreamProvider
	newAppStreamProviderMutex       sync.RWMutex
	newAppStreamProviderArgsForCall []struct {
		appGUID string
	}
	newAppStreamProviderReturns struct {
		result1 cf.AppStreamProvider
	}
	newAppStreamProviderReturnsOnCall map[int]struct {
		result1 cf.AppStreamProvider
	}
	GetTokenStub        func() (token string, authError error)
	getTokenMutex       sync.RWMutex
	getTokenArgsForCall []struct{}
	getTokenReturns     struct {
		result1 string
		result2 error
	}
	getTokenReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	RefreshAuthTokenStub        func() (token string, authError error)
	refreshAuthTokenMutex       sync.RWMutex
	refreshAuthTokenArgsForCall []struct{}
	refreshAuthTokenReturns     struct {
		result1 string
		result2 error
	}
	refreshAuthTokenReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	DopplerEndpointStub        func() string
	dopplerEndpointMutex       sync.RWMutex
	dopplerEndpointArgsForCall []struct{}
	dopplerEndpointReturns     struct {
		result1 string
	}
	dopplerEndpointReturnsOnCall map[int]struct {
		result1 string
	}
	NewLogCacheClientStub        func() cf.LogCacheClient
	newLogCacheClientMutex       sync.RWMutex
	newLogCacheClientArgsForCall []struct{}
	newLogCacheClientReturns     struct {
		result1 cf.LogCacheClient
	}
	newLogCacheClientReturnsOnCall map[int]struct {
		result1 cf.LogCacheClient
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) ListAppsWithSpaceAndOrg() ([]cfclient.App, error) {
	fake.listAppsWithSpaceAndOrgMutex.Lock()
	ret, specificReturn := fake.listAppsWithSpaceAndOrgReturnsOnCall[len(fake.listAppsWithSpaceAndOrgArgsForCall)]
	fake.listAppsWithSpaceAndOrgArgsForCall = append(fake.listAppsWithSpaceAndOrgArgsForCall, struct{}{})
	fake.recordInvocation("ListAppsWithSpaceAndOrg", []interface{}{})
	fake.listAppsWithSpaceAndOrgMutex.Unlock()
	if fake.ListAppsWithSpaceAndOrgStub != nil {
		return fake.ListAppsWithSpaceAndOrgStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.listAppsWithSpaceAndOrgReturns.result1, fake.listAppsWithSpaceAndOrgReturns.result2
}

func (fake *FakeClient) ListAppsWithSpaceAndOrgCallCount() int {
	fake.listAppsWithSpaceAndOrgMutex.RLock()
	defer fake.listAppsWithSpaceAndOrgMutex.RUnlock()
	return len(fake.listAppsWithSpaceAndOrgArgsForCall)
}

func (fake *FakeClient) ListAppsWithSpaceAndOrgReturns(result1 []cfclient.App, result2 error) {
	fake.ListAppsWithSpaceAndOrgStub = nil
	fake.listAppsWithSpaceAndOrgReturns = struct {
		result1 []cfclient.App
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListAppsWithSpaceAndOrgReturnsOnCall(i int, result1 []cfclient.App, result2 error) {
	fake.ListAppsWithSpaceAndOrgStub = nil
	if fake.listAppsWithSpaceAndOrgReturnsOnCall == nil {
		fake.listAppsWithSpaceAndOrgReturnsOnCall = make(map[int]struct {
			result1 []cfclient.App
			result2 error
		})
	}
	fake.listAppsWithSpaceAndOrgReturnsOnCall[i] = struct {
		result1 []cfclient.App
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListServicesWithSpaceAndOrg() ([]cf.ServiceInstance, error) {
	fake.listServicesWithSpaceAndOrgMutex.Lock()
	ret, specificReturn := fake.listServicesWithSpaceAndOrgReturnsOnCall[len(fake.listServicesWithSpaceAndOrgArgsForCall)]
	fake.listServicesWithSpaceAndOrgArgsForCall = append(fake.listServicesWithSpaceAndOrgArgsForCall, struct{}{})
	fake.recordInvocation("ListServicesWithSpaceAndOrg", []interface{}{})
	fake.listServicesWithSpaceAndOrgMutex.Unlock()
	if fake.ListServicesWithSpaceAndOrgStub != nil {
		return fake.ListServicesWithSpaceAndOrgStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.listServicesWithSpaceAndOrgReturns.result1, fake.listServicesWithSpaceAndOrgReturns.result2
}

func (fake *FakeClient) ListServicesWithSpaceAndOrgCallCount() int {
	fake.listServicesWithSpaceAndOrgMutex.RLock()
	defer fake.listServicesWithSpaceAndOrgMutex.RUnlock()
	return len(fake.listServicesWithSpaceAndOrgArgsForCall)
}

func (fake *FakeClient) ListServicesWithSpaceAndOrgReturns(result1 []cf.ServiceInstance, result2 error) {
	fake.ListServicesWithSpaceAndOrgStub = nil
	fake.listServicesWithSpaceAndOrgReturns = struct {
		result1 []cf.ServiceInstance
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListServicesWithSpaceAndOrgReturnsOnCall(i int, result1 []cf.ServiceInstance, result2 error) {
	fake.ListServicesWithSpaceAndOrgStub = nil
	if fake.listServicesWithSpaceAndOrgReturnsOnCall == nil {
		fake.listServicesWithSpaceAndOrgReturnsOnCall = make(map[int]struct {
			result1 []cf.ServiceInstance
			result2 error
		})
	}
	fake.listServicesWithSpaceAndOrgReturnsOnCall[i] = struct {
		result1 []cf.ServiceInstance
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) NewAppStreamProvider(appGUID string) cf.AppStreamProvider {
	fake.newAppStreamProviderMutex.Lock()
	ret, specificReturn := fake.newAppStreamProviderReturnsOnCall[len(fake.newAppStreamProviderArgsForCall)]
	fake.newAppStreamProviderArgsForCall = append(fake.newAppStreamProviderArgsForCall, struct {
		appGUID string
	}{appGUID})
	fake.recordInvocation("NewAppStreamProvider", []interface{}{appGUID})
	fake.newAppStreamProviderMutex.Unlock()
	if fake.NewAppStreamProviderStub != nil {
		return fake.NewAppStreamProviderStub(appGUID)
	}
	if specificReturn {
		return ret.result1
	}
	return fake.newAppStreamProviderReturns.result1
}

func (fake *FakeClient) NewAppStreamProviderCallCount() int {
	fake.newAppStreamProviderMutex.RLock()
	defer fake.newAppStreamProviderMutex.RUnlock()
	return len(fake.newAppStreamProviderArgsForCall)
}

func (fake *FakeClient) NewAppStreamProviderArgsForCall(i int) string {
	fake.newAppStreamProviderMutex.RLock()
	defer fake.newAppStreamProviderMutex.RUnlock()
	return fake.newAppStreamProviderArgsForCall[i].appGUID
}

func (fake *FakeClient) NewAppStreamProviderReturns(result1 cf.AppStreamProvider) {
	fake.NewAppStreamProviderStub = nil
	fake.newAppStreamProviderReturns = struct {
		result1 cf.AppStreamProvider
	}{result1}
}

func (fake *FakeClient) NewAppStreamProviderReturnsOnCall(i int, result1 cf.AppStreamProvider) {
	fake.NewAppStreamProviderStub = nil
	if fake.newAppStreamProviderReturnsOnCall == nil {
		fake.newAppStreamProviderReturnsOnCall = make(map[int]struct {
			result1 cf.AppStreamProvider
		})
	}
	fake.newAppStreamProviderReturnsOnCall[i] = struct {
		result1 cf.AppStreamProvider
	}{result1}
}

func (fake *FakeClient) GetToken() (token string, authError error) {
	fake.getTokenMutex.Lock()
	ret, specificReturn := fake.getTokenReturnsOnCall[len(fake.getTokenArgsForCall)]
	fake.getTokenArgsForCall = append(fake.getTokenArgsForCall, struct{}{})
	fake.recordInvocation("GetToken", []interface{}{})
	fake.getTokenMutex.Unlock()
	if fake.GetTokenStub != nil {
		return fake.GetTokenStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.getTokenReturns.result1, fake.getTokenReturns.result2
}

func (fake *FakeClient) GetTokenCallCount() int {
	fake.getTokenMutex.RLock()
	defer fake.getTokenMutex.RUnlock()
	return len(fake.getTokenArgsForCall)
}

func (fake *FakeClient) GetTokenReturns(result1 string, result2 error) {
	fake.GetTokenStub = nil
	fake.getTokenReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetTokenReturnsOnCall(i int, result1 string, result2 error) {
	fake.GetTokenStub = nil
	if fake.getTokenReturnsOnCall == nil {
		fake.getTokenReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getTokenReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) RefreshAuthToken() (token string, authError error) {
	fake.refreshAuthTokenMutex.Lock()
	ret, specificReturn := fake.refreshAuthTokenReturnsOnCall[len(fake.refreshAuthTokenArgsForCall)]
	fake.refreshAuthTokenArgsForCall = append(fake.refreshAuthTokenArgsForCall, struct{}{})
	fake.recordInvocation("RefreshAuthToken", []interface{}{})
	fake.refreshAuthTokenMutex.Unlock()
	if fake.RefreshAuthTokenStub != nil {
		return fake.RefreshAuthTokenStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fake.refreshAuthTokenReturns.result1, fake.refreshAuthTokenReturns.result2
}

func (fake *FakeClient) RefreshAuthTokenCallCount() int {
	fake.refreshAuthTokenMutex.RLock()
	defer fake.refreshAuthTokenMutex.RUnlock()
	return len(fake.refreshAuthTokenArgsForCall)
}

func (fake *FakeClient) RefreshAuthTokenReturns(result1 string, result2 error) {
	fake.RefreshAuthTokenStub = nil
	fake.refreshAuthTokenReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) RefreshAuthTokenReturnsOnCall(i int, result1 string, result2 error) {
	fake.RefreshAuthTokenStub = nil
	if fake.refreshAuthTokenReturnsOnCall == nil {
		fake.refreshAuthTokenReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.refreshAuthTokenReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) DopplerEndpoint() string {
	fake.dopplerEndpointMutex.Lock()
	ret, specificReturn := fake.dopplerEndpointReturnsOnCall[len(fake.dopplerEndpointArgsForCall)]
	fake.dopplerEndpointArgsForCall = append(fake.dopplerEndpointArgsForCall, struct{}{})
	fake.recordInvocation("DopplerEndpoint", []interface{}{})
	fake.dopplerEndpointMutex.Unlock()
	if fake.DopplerEndpointStub != nil {
		return fake.DopplerEndpointStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.dopplerEndpointReturns.result1
}

func (fake *FakeClient) DopplerEndpointCallCount() int {
	fake.dopplerEndpointMutex.RLock()
	defer fake.dopplerEndpointMutex.RUnlock()
	return len(fake.dopplerEndpointArgsForCall)
}

func (fake *FakeClient) DopplerEndpointReturns(result1 string) {
	fake.DopplerEndpointStub = nil
	fake.dopplerEndpointReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeClient) DopplerEndpointReturnsOnCall(i int, result1 string) {
	fake.DopplerEndpointStub = nil
	if fake.dopplerEndpointReturnsOnCall == nil {
		fake.dopplerEndpointReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.dopplerEndpointReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeClient) NewLogCacheClient() cf.LogCacheClient {
	fake.newLogCacheClientMutex.Lock()
	ret, specificReturn := fake.newLogCacheClientReturnsOnCall[len(fake.newLogCacheClientArgsForCall)]
	fake.newLogCacheClientArgsForCall = append(fake.newLogCacheClientArgsForCall, struct{}{})
	fake.recordInvocation("NewLogCacheClient", []interface{}{})
	fake.newLogCacheClientMutex.Unlock()
	if fake.NewLogCacheClientStub != nil {
		return fake.NewLogCacheClientStub()
	}
	if specificReturn {
		return ret.result1
	}
	return fake.newLogCacheClientReturns.result1
}

func (fake *FakeClient) NewLogCacheClientCallCount() int {
	fake.newLogCacheClientMutex.RLock()
	defer fake.newLogCacheClientMutex.RUnlock()
	return len(fake.newLogCacheClientArgsForCall)
}

func (fake *FakeClient) NewLogCacheClientReturns(result1 cf.LogCacheClient) {
	fake.NewLogCacheClientStub = nil
	fake.newLogCacheClientReturns = struct {
		result1 cf.LogCacheClient
	}{result1}
}

func (fake *FakeClient) NewLogCacheClientReturnsOnCall(i int, result1 cf.LogCacheClient) {
	fake.NewLogCacheClientStub = nil
	if fake.newLogCacheClientReturnsOnCall == nil {
		fake.newLogCacheClientReturnsOnCall = make(map[int]struct {
			result1 cf.LogCacheClient
		})
	}
	fake.newLogCacheClientReturnsOnCall[i] = struct {
		result1 cf.LogCacheClient
	}{result1}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.listAppsWithSpaceAndOrgMutex.RLock()
	defer fake.listAppsWithSpaceAndOrgMutex.RUnlock()
	fake.listServicesWithSpaceAndOrgMutex.RLock()
	defer fake.listServicesWithSpaceAndOrgMutex.RUnlock()
	fake.newAppStreamProviderMutex.RLock()
	defer fake.newAppStreamProviderMutex.RUnlock()
	fake.getTokenMutex.RLock()
	defer fake.getTokenMutex.RUnlock()
	fake.refreshAuthTokenMutex.RLock()
	defer fake.refreshAuthTokenMutex.RUnlock()
	fake.dopplerEndpointMutex.RLock()
	defer fake.dopplerEndpointMutex.RUnlock()
	fake.newLogCacheClientMutex.RLock()
	defer fake.newLogCacheClientMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cf.Client = new(FakeClient)
