// Code generated by counterfeiter. DO NOT EDIT.
package mocks

import (
	"sync"

	"github.com/alphagov/paas-prometheus-exporter/cf"
)

type FakeClient struct {
	DopplerEndpointStub        func() string
	dopplerEndpointMutex       sync.RWMutex
	dopplerEndpointArgsForCall []struct {
	}
	dopplerEndpointReturns struct {
		result1 string
	}
	dopplerEndpointReturnsOnCall map[int]struct {
		result1 string
	}
	GetTokenStub        func() (string, error)
	getTokenMutex       sync.RWMutex
	getTokenArgsForCall []struct {
	}
	getTokenReturns struct {
		result1 string
		result2 error
	}
	getTokenReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	ListProcessWithAppsSpaceAndOrgStub        func() ([]cf.AppWithProcesses, error)
	listProcessWithAppsSpaceAndOrgMutex       sync.RWMutex
	listProcessWithAppsSpaceAndOrgArgsForCall []struct {
	}
	listProcessWithAppsSpaceAndOrgReturns struct {
		result1 []cf.AppWithProcesses
		result2 error
	}
	listProcessWithAppsSpaceAndOrgReturnsOnCall map[int]struct {
		result1 []cf.AppWithProcesses
		result2 error
	}
	ListServicesWithSpaceAndOrgStub        func() ([]cf.ServiceInstance, error)
	listServicesWithSpaceAndOrgMutex       sync.RWMutex
	listServicesWithSpaceAndOrgArgsForCall []struct {
	}
	listServicesWithSpaceAndOrgReturns struct {
		result1 []cf.ServiceInstance
		result2 error
	}
	listServicesWithSpaceAndOrgReturnsOnCall map[int]struct {
		result1 []cf.ServiceInstance
		result2 error
	}
	NewAppStreamProviderStub        func(string) cf.AppStreamProvider
	newAppStreamProviderMutex       sync.RWMutex
	newAppStreamProviderArgsForCall []struct {
		arg1 string
	}
	newAppStreamProviderReturns struct {
		result1 cf.AppStreamProvider
	}
	newAppStreamProviderReturnsOnCall map[int]struct {
		result1 cf.AppStreamProvider
	}
	NewLogCacheClientStub        func() cf.LogCacheClient
	newLogCacheClientMutex       sync.RWMutex
	newLogCacheClientArgsForCall []struct {
	}
	newLogCacheClientReturns struct {
		result1 cf.LogCacheClient
	}
	newLogCacheClientReturnsOnCall map[int]struct {
		result1 cf.LogCacheClient
	}
	RefreshAuthTokenStub        func() (string, error)
	refreshAuthTokenMutex       sync.RWMutex
	refreshAuthTokenArgsForCall []struct {
	}
	refreshAuthTokenReturns struct {
		result1 string
		result2 error
	}
	refreshAuthTokenReturnsOnCall map[int]struct {
		result1 string
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeClient) DopplerEndpoint() string {
	fake.dopplerEndpointMutex.Lock()
	ret, specificReturn := fake.dopplerEndpointReturnsOnCall[len(fake.dopplerEndpointArgsForCall)]
	fake.dopplerEndpointArgsForCall = append(fake.dopplerEndpointArgsForCall, struct {
	}{})
	fake.recordInvocation("DopplerEndpoint", []interface{}{})
	fake.dopplerEndpointMutex.Unlock()
	if fake.DopplerEndpointStub != nil {
		return fake.DopplerEndpointStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.dopplerEndpointReturns
	return fakeReturns.result1
}

func (fake *FakeClient) DopplerEndpointCallCount() int {
	fake.dopplerEndpointMutex.RLock()
	defer fake.dopplerEndpointMutex.RUnlock()
	return len(fake.dopplerEndpointArgsForCall)
}

func (fake *FakeClient) DopplerEndpointCalls(stub func() string) {
	fake.dopplerEndpointMutex.Lock()
	defer fake.dopplerEndpointMutex.Unlock()
	fake.DopplerEndpointStub = stub
}

func (fake *FakeClient) DopplerEndpointReturns(result1 string) {
	fake.dopplerEndpointMutex.Lock()
	defer fake.dopplerEndpointMutex.Unlock()
	fake.DopplerEndpointStub = nil
	fake.dopplerEndpointReturns = struct {
		result1 string
	}{result1}
}

func (fake *FakeClient) DopplerEndpointReturnsOnCall(i int, result1 string) {
	fake.dopplerEndpointMutex.Lock()
	defer fake.dopplerEndpointMutex.Unlock()
	fake.DopplerEndpointStub = nil
	if fake.dopplerEndpointReturnsOnCall == nil {
		fake.dopplerEndpointReturnsOnCall = make(map[int]struct {
			result1 string
		})
	}
	fake.dopplerEndpointReturnsOnCall[i] = struct {
		result1 string
	}{result1}
}

func (fake *FakeClient) GetToken() (string, error) {
	fake.getTokenMutex.Lock()
	ret, specificReturn := fake.getTokenReturnsOnCall[len(fake.getTokenArgsForCall)]
	fake.getTokenArgsForCall = append(fake.getTokenArgsForCall, struct {
	}{})
	fake.recordInvocation("GetToken", []interface{}{})
	fake.getTokenMutex.Unlock()
	if fake.GetTokenStub != nil {
		return fake.GetTokenStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.getTokenReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) GetTokenCallCount() int {
	fake.getTokenMutex.RLock()
	defer fake.getTokenMutex.RUnlock()
	return len(fake.getTokenArgsForCall)
}

func (fake *FakeClient) GetTokenCalls(stub func() (string, error)) {
	fake.getTokenMutex.Lock()
	defer fake.getTokenMutex.Unlock()
	fake.GetTokenStub = stub
}

func (fake *FakeClient) GetTokenReturns(result1 string, result2 error) {
	fake.getTokenMutex.Lock()
	defer fake.getTokenMutex.Unlock()
	fake.GetTokenStub = nil
	fake.getTokenReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) GetTokenReturnsOnCall(i int, result1 string, result2 error) {
	fake.getTokenMutex.Lock()
	defer fake.getTokenMutex.Unlock()
	fake.GetTokenStub = nil
	if fake.getTokenReturnsOnCall == nil {
		fake.getTokenReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.getTokenReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListProcessWithAppsSpaceAndOrg() ([]cf.AppWithProcesses, error) {
	fake.listProcessWithAppsSpaceAndOrgMutex.Lock()
	ret, specificReturn := fake.listProcessWithAppsSpaceAndOrgReturnsOnCall[len(fake.listProcessWithAppsSpaceAndOrgArgsForCall)]
	fake.listProcessWithAppsSpaceAndOrgArgsForCall = append(fake.listProcessWithAppsSpaceAndOrgArgsForCall, struct {
	}{})
	fake.recordInvocation("ListProcessWithAppsSpaceAndOrg", []interface{}{})
	fake.listProcessWithAppsSpaceAndOrgMutex.Unlock()
	if fake.ListProcessWithAppsSpaceAndOrgStub != nil {
		return fake.ListProcessWithAppsSpaceAndOrgStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.listProcessWithAppsSpaceAndOrgReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) ListProcessWithAppsSpaceAndOrgCallCount() int {
	fake.listProcessWithAppsSpaceAndOrgMutex.RLock()
	defer fake.listProcessWithAppsSpaceAndOrgMutex.RUnlock()
	return len(fake.listProcessWithAppsSpaceAndOrgArgsForCall)
}

func (fake *FakeClient) ListProcessWithAppsSpaceAndOrgCalls(stub func() ([]cf.AppWithProcesses, error)) {
	fake.listProcessWithAppsSpaceAndOrgMutex.Lock()
	defer fake.listProcessWithAppsSpaceAndOrgMutex.Unlock()
	fake.ListProcessWithAppsSpaceAndOrgStub = stub
}

func (fake *FakeClient) ListProcessWithAppsSpaceAndOrgReturns(result1 []cf.AppWithProcesses, result2 error) {
	fake.listProcessWithAppsSpaceAndOrgMutex.Lock()
	defer fake.listProcessWithAppsSpaceAndOrgMutex.Unlock()
	fake.ListProcessWithAppsSpaceAndOrgStub = nil
	fake.listProcessWithAppsSpaceAndOrgReturns = struct {
		result1 []cf.AppWithProcesses
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListProcessWithAppsSpaceAndOrgReturnsOnCall(i int, result1 []cf.AppWithProcesses, result2 error) {
	fake.listProcessWithAppsSpaceAndOrgMutex.Lock()
	defer fake.listProcessWithAppsSpaceAndOrgMutex.Unlock()
	fake.ListProcessWithAppsSpaceAndOrgStub = nil
	if fake.listProcessWithAppsSpaceAndOrgReturnsOnCall == nil {
		fake.listProcessWithAppsSpaceAndOrgReturnsOnCall = make(map[int]struct {
			result1 []cf.AppWithProcesses
			result2 error
		})
	}
	fake.listProcessWithAppsSpaceAndOrgReturnsOnCall[i] = struct {
		result1 []cf.AppWithProcesses
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListServicesWithSpaceAndOrg() ([]cf.ServiceInstance, error) {
	fake.listServicesWithSpaceAndOrgMutex.Lock()
	ret, specificReturn := fake.listServicesWithSpaceAndOrgReturnsOnCall[len(fake.listServicesWithSpaceAndOrgArgsForCall)]
	fake.listServicesWithSpaceAndOrgArgsForCall = append(fake.listServicesWithSpaceAndOrgArgsForCall, struct {
	}{})
	fake.recordInvocation("ListServicesWithSpaceAndOrg", []interface{}{})
	fake.listServicesWithSpaceAndOrgMutex.Unlock()
	if fake.ListServicesWithSpaceAndOrgStub != nil {
		return fake.ListServicesWithSpaceAndOrgStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.listServicesWithSpaceAndOrgReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) ListServicesWithSpaceAndOrgCallCount() int {
	fake.listServicesWithSpaceAndOrgMutex.RLock()
	defer fake.listServicesWithSpaceAndOrgMutex.RUnlock()
	return len(fake.listServicesWithSpaceAndOrgArgsForCall)
}

func (fake *FakeClient) ListServicesWithSpaceAndOrgCalls(stub func() ([]cf.ServiceInstance, error)) {
	fake.listServicesWithSpaceAndOrgMutex.Lock()
	defer fake.listServicesWithSpaceAndOrgMutex.Unlock()
	fake.ListServicesWithSpaceAndOrgStub = stub
}

func (fake *FakeClient) ListServicesWithSpaceAndOrgReturns(result1 []cf.ServiceInstance, result2 error) {
	fake.listServicesWithSpaceAndOrgMutex.Lock()
	defer fake.listServicesWithSpaceAndOrgMutex.Unlock()
	fake.ListServicesWithSpaceAndOrgStub = nil
	fake.listServicesWithSpaceAndOrgReturns = struct {
		result1 []cf.ServiceInstance
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) ListServicesWithSpaceAndOrgReturnsOnCall(i int, result1 []cf.ServiceInstance, result2 error) {
	fake.listServicesWithSpaceAndOrgMutex.Lock()
	defer fake.listServicesWithSpaceAndOrgMutex.Unlock()
	fake.ListServicesWithSpaceAndOrgStub = nil
	if fake.listServicesWithSpaceAndOrgReturnsOnCall == nil {
		fake.listServicesWithSpaceAndOrgReturnsOnCall = make(map[int]struct {
			result1 []cf.ServiceInstance
			result2 error
		})
	}
	fake.listServicesWithSpaceAndOrgReturnsOnCall[i] = struct {
		result1 []cf.ServiceInstance
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) NewAppStreamProvider(arg1 string) cf.AppStreamProvider {
	fake.newAppStreamProviderMutex.Lock()
	ret, specificReturn := fake.newAppStreamProviderReturnsOnCall[len(fake.newAppStreamProviderArgsForCall)]
	fake.newAppStreamProviderArgsForCall = append(fake.newAppStreamProviderArgsForCall, struct {
		arg1 string
	}{arg1})
	fake.recordInvocation("NewAppStreamProvider", []interface{}{arg1})
	fake.newAppStreamProviderMutex.Unlock()
	if fake.NewAppStreamProviderStub != nil {
		return fake.NewAppStreamProviderStub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.newAppStreamProviderReturns
	return fakeReturns.result1
}

func (fake *FakeClient) NewAppStreamProviderCallCount() int {
	fake.newAppStreamProviderMutex.RLock()
	defer fake.newAppStreamProviderMutex.RUnlock()
	return len(fake.newAppStreamProviderArgsForCall)
}

func (fake *FakeClient) NewAppStreamProviderCalls(stub func(string) cf.AppStreamProvider) {
	fake.newAppStreamProviderMutex.Lock()
	defer fake.newAppStreamProviderMutex.Unlock()
	fake.NewAppStreamProviderStub = stub
}

func (fake *FakeClient) NewAppStreamProviderArgsForCall(i int) string {
	fake.newAppStreamProviderMutex.RLock()
	defer fake.newAppStreamProviderMutex.RUnlock()
	argsForCall := fake.newAppStreamProviderArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeClient) NewAppStreamProviderReturns(result1 cf.AppStreamProvider) {
	fake.newAppStreamProviderMutex.Lock()
	defer fake.newAppStreamProviderMutex.Unlock()
	fake.NewAppStreamProviderStub = nil
	fake.newAppStreamProviderReturns = struct {
		result1 cf.AppStreamProvider
	}{result1}
}

func (fake *FakeClient) NewAppStreamProviderReturnsOnCall(i int, result1 cf.AppStreamProvider) {
	fake.newAppStreamProviderMutex.Lock()
	defer fake.newAppStreamProviderMutex.Unlock()
	fake.NewAppStreamProviderStub = nil
	if fake.newAppStreamProviderReturnsOnCall == nil {
		fake.newAppStreamProviderReturnsOnCall = make(map[int]struct {
			result1 cf.AppStreamProvider
		})
	}
	fake.newAppStreamProviderReturnsOnCall[i] = struct {
		result1 cf.AppStreamProvider
	}{result1}
}

func (fake *FakeClient) NewLogCacheClient() cf.LogCacheClient {
	fake.newLogCacheClientMutex.Lock()
	ret, specificReturn := fake.newLogCacheClientReturnsOnCall[len(fake.newLogCacheClientArgsForCall)]
	fake.newLogCacheClientArgsForCall = append(fake.newLogCacheClientArgsForCall, struct {
	}{})
	fake.recordInvocation("NewLogCacheClient", []interface{}{})
	fake.newLogCacheClientMutex.Unlock()
	if fake.NewLogCacheClientStub != nil {
		return fake.NewLogCacheClientStub()
	}
	if specificReturn {
		return ret.result1
	}
	fakeReturns := fake.newLogCacheClientReturns
	return fakeReturns.result1
}

func (fake *FakeClient) NewLogCacheClientCallCount() int {
	fake.newLogCacheClientMutex.RLock()
	defer fake.newLogCacheClientMutex.RUnlock()
	return len(fake.newLogCacheClientArgsForCall)
}

func (fake *FakeClient) NewLogCacheClientCalls(stub func() cf.LogCacheClient) {
	fake.newLogCacheClientMutex.Lock()
	defer fake.newLogCacheClientMutex.Unlock()
	fake.NewLogCacheClientStub = stub
}

func (fake *FakeClient) NewLogCacheClientReturns(result1 cf.LogCacheClient) {
	fake.newLogCacheClientMutex.Lock()
	defer fake.newLogCacheClientMutex.Unlock()
	fake.NewLogCacheClientStub = nil
	fake.newLogCacheClientReturns = struct {
		result1 cf.LogCacheClient
	}{result1}
}

func (fake *FakeClient) NewLogCacheClientReturnsOnCall(i int, result1 cf.LogCacheClient) {
	fake.newLogCacheClientMutex.Lock()
	defer fake.newLogCacheClientMutex.Unlock()
	fake.NewLogCacheClientStub = nil
	if fake.newLogCacheClientReturnsOnCall == nil {
		fake.newLogCacheClientReturnsOnCall = make(map[int]struct {
			result1 cf.LogCacheClient
		})
	}
	fake.newLogCacheClientReturnsOnCall[i] = struct {
		result1 cf.LogCacheClient
	}{result1}
}

func (fake *FakeClient) RefreshAuthToken() (string, error) {
	fake.refreshAuthTokenMutex.Lock()
	ret, specificReturn := fake.refreshAuthTokenReturnsOnCall[len(fake.refreshAuthTokenArgsForCall)]
	fake.refreshAuthTokenArgsForCall = append(fake.refreshAuthTokenArgsForCall, struct {
	}{})
	fake.recordInvocation("RefreshAuthToken", []interface{}{})
	fake.refreshAuthTokenMutex.Unlock()
	if fake.RefreshAuthTokenStub != nil {
		return fake.RefreshAuthTokenStub()
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	fakeReturns := fake.refreshAuthTokenReturns
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeClient) RefreshAuthTokenCallCount() int {
	fake.refreshAuthTokenMutex.RLock()
	defer fake.refreshAuthTokenMutex.RUnlock()
	return len(fake.refreshAuthTokenArgsForCall)
}

func (fake *FakeClient) RefreshAuthTokenCalls(stub func() (string, error)) {
	fake.refreshAuthTokenMutex.Lock()
	defer fake.refreshAuthTokenMutex.Unlock()
	fake.RefreshAuthTokenStub = stub
}

func (fake *FakeClient) RefreshAuthTokenReturns(result1 string, result2 error) {
	fake.refreshAuthTokenMutex.Lock()
	defer fake.refreshAuthTokenMutex.Unlock()
	fake.RefreshAuthTokenStub = nil
	fake.refreshAuthTokenReturns = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) RefreshAuthTokenReturnsOnCall(i int, result1 string, result2 error) {
	fake.refreshAuthTokenMutex.Lock()
	defer fake.refreshAuthTokenMutex.Unlock()
	fake.RefreshAuthTokenStub = nil
	if fake.refreshAuthTokenReturnsOnCall == nil {
		fake.refreshAuthTokenReturnsOnCall = make(map[int]struct {
			result1 string
			result2 error
		})
	}
	fake.refreshAuthTokenReturnsOnCall[i] = struct {
		result1 string
		result2 error
	}{result1, result2}
}

func (fake *FakeClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	fake.dopplerEndpointMutex.RLock()
	defer fake.dopplerEndpointMutex.RUnlock()
	fake.getTokenMutex.RLock()
	defer fake.getTokenMutex.RUnlock()
	fake.listProcessWithAppsSpaceAndOrgMutex.RLock()
	defer fake.listProcessWithAppsSpaceAndOrgMutex.RUnlock()
	fake.listServicesWithSpaceAndOrgMutex.RLock()
	defer fake.listServicesWithSpaceAndOrgMutex.RUnlock()
	fake.newAppStreamProviderMutex.RLock()
	defer fake.newAppStreamProviderMutex.RUnlock()
	fake.newLogCacheClientMutex.RLock()
	defer fake.newLogCacheClientMutex.RUnlock()
	fake.refreshAuthTokenMutex.RLock()
	defer fake.refreshAuthTokenMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ cf.Client = new(FakeClient)
