name: ci

on: [push]

jobs:

  build:
    name: build
    runs-on: ubuntu-latest
    steps:
      - name: setup
        uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe
        with:
          go-version: '1.18'

      - name: checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9

      - name: test
        run: make test
